name: crypto_currency
description: An application for displaying crypto currencies rates.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clock: ^1.0.1
  cupertino_icons: ^0.1.3
  http: ^0.13.4
  intl : ^0.16.1
  kiwi: ^2.0.1
  json_annotation: ^3.1.0
  flutter_svg: ^0.19.1
  flutter_bloc_patterns: ^0.6.0
  sqflite: ^1.3.0
  sqlite_at_runtime: ^0.0.1
  provider:  ^4.0.1
  shared_preferences: ^0.5.4+6
  background_fetch: ^1.0.1

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  lint: ^1.3.0
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/secrets/